### ISSUE TITLE
labels.csv

### ISSUE THREAD

**Issue by rohanphil** [sigmaai/behavioral-cloning-research#2]
Hey, would it be possible for you to give me an idea what the contents of the labels.csv file that is specified in your train.py code is?

**Comment by NeilNie** [comment]
Hey Rohan,

Thanks for reaching out. The `labels.csv` file contains the ground truth steering data and the image location on my hard drive. It has been a little while since I did this project. I will dig into my hard drive and share that file with you. 

The dataset that I am using is the Udacity self driving dataset. https://github.com/udacity/self-driving-car/tree/master/datasets I believe you can improve/augment the dataset if you want. Another really nice dataset for this application is the Apollo dataset: http://apolloscape.auto/ I hope this helps.

**Comment by NeilNie** [comment]
I have created a dropbox file and it includes the csv file that you are looking for as well as all of the images associated with the csv file. The file is poorly named, it’s called labels.csv. It’s actually the validation dataset for testing your trained models. https://www.dropbox.com/s/rg52l3kydwigq9q/test.zip?dl=0
